# Generated by Django 5.0.3 on 2024-03-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('último_nome', models.CharField(max_length=40)),
                ('telefone', models.CharField(max_length=35)),
                ('genero', models.CharField(max_length=10)),
            ],
        ),
    ]
